### ISSUE TITLE
api.printerStats.printerBedTempActual and api.printerStats.printerTool0TempActual

### ISSUE THREAD

**Issue by DerNeuanfang** [chunkysteveo/OctoPrintAPI#15]
Hi,
I using 
api.printerStats.printerBedTempActual
and 
api.printerStats.printerTool0TempActual

to get the Temp of my Printer, but it is allways 0.00

**Comment by chunkysteveo** [comment]
Hi @DerNeuanfang - does the example "hello world" sketch work for you - does it report back other stats about the printer? Are you using an ESP8266 or an ESP32?

**Comment by DerNeuanfang** [comment]
hi,
it worked now. IDK what i did wrong yesterday, but if i delete WiFi.mode(); it works fine.

Thanks for this. :-)

**Comment by chunkysteveo** [comment]
Glad it's sorted, sounds like it wasn't connecting to the printer at all? No problem, happy printing!!
