### ISSUE TITLE
OctoPrint API can't get "job volume"

### ISSUE THREAD

**Issue by cryptooth** [chunkysteveo/OctoPrintAPI#16]
I can't get "job volume" from /api/job

OctoPrint Version 1.3.11

here is my json output:

```
{
  "job": {
    "averagePrintTime": null, 
    "estimatedPrintTime": 13998.720965267157, 
    "filament": {
      "tool0": {
        "length": 13039.22874999944, 
        "volume": 0.0
      }
    }, 
    "file": {
      "date": 1562264575, 
      "display": "AI3M_Apple_Watch_Dock_shell.gcode", 
      "name": "AI3M_Apple_Watch_Dock_shell.gcode", 
      "origin": "local", 
      "path": "AI3M_Apple_Watch_Dock_shell.gcode", 
      "size": 8588159
    }, 
    "lastPrintTime": null, 
    "user": "kayhanbelek"
  }, 
  "progress": {
    "completion": 54.590617150893465, 
    "filepos": 4688329, 
    "printTime": 10048, 
    "printTimeLeft": 8393, 
    "printTimeLeftOrigin": "estimate"
  }, 
  "state": "Printing"
}
```

**Comment by chunkysteveo** [comment]
That looks like Octoprint API is not providing the volume for some reason, not that my library is causing an issue. The JSON from Octoprint should have the value if present. Can you see the volume of the part in the Files list of the web GUI sidebar? See image below:

![FireShot Capture 035 - P3Steel Toolson  OctoPrint  - 192 168 1 113](https://user-images.githubusercontent.com/14663002/60708618-61be6a80-9f06-11e9-8ff1-791b08c92b1a.png)

Click the down arrow to reveal the stats about the file that Octoprint can read. Can you forward me your gcode file as an attachment to this issue? I tested my own gcode files and deleted the volume comment that my slicer added to see if that did anything. Looks like Octoprint works out the volume. 

If you could check your volume from the web, and forward your gcode fille?

Steve
