### ISSUE TITLE
WPA2 or Ethernet access

### ISSUE THREAD

**Issue by mullinsen** [chunkysteveo/OctoPrintAPI#2]
Hi,
I was hoping to use the OctoPrintAPI for my Bachelors Thesis. However, to access the wireless network, I need to provide SSID, username, and password. Is this possible with the current library?
If not, is there a possibility of using Ethernet?

Thank you

**Comment by chunkysteveo** [comment]
Hi,

I assume with getting a degree, and needing a username you are trying to connect to your Uni's wireless network? The examples provided are for an ESP8266 which connects to WiFi using a wireless SSID and password, no username.

In theory it should be possible to use an ethernet shield on an Adruino, but i've not got one of those to test or try - so cannot comment? The library assumes you are connected and it can speak with the OctoPrint server, so using an ethernet shield should work. How is your OctoPrint server connected and how do you connect to it at the moment?

Steve

**Comment by mullinsen** [comment]
Thank you for a swift response.
Yes, I am trying to connect to the eduroam network. So far, I am not finding any ways to use WiFiClient in a WPA2 Enterprise network. To my knowledge, I agree that ethernet in theory should work.

If you are interested in some background info, the thesis is in short to build a serial production robot for a Prusa i3 MK3 printer. The task is to feed an available printer with a ready print sheet, start the printing process, and unload when the print is done - and so on. This is why I found this OctoPrintAPI library to be the best solution, at least to provide the with the printer information.

We are yet to recieve the 3D-printer itself, expecting it to arrive within the next 2 weeks. Basically, we have set up the OctoPrint server on a Raspberry Pi connected with ethernet, with a virtual printer plugin installed. (I have assumed that the OctoPrintAPI will probably work with a virtual printer as well). We are yet to be able to establish a connection between OctoPrint and Arduino, hoping this library can work for us.
In case you didn't notice - we are in the beginning stages of the thesis, and are still fairly new to Octoprint, GitHub and Arduino beyond the simplest simple. 

Michael

**Comment by chunkysteveo** [comment]
Hi Michael,

Sounds like a great project to work on! From what I have just read, ESP8266 and WPA2 Enterprise was tried and appears to be abandoned? - https://github.com/esp8266/Arduino/issues/1032 if you read the last few posts. It sounded promising, but no simple "hello world I work" example to confirm it works, I think it is dead.

Ethernet access should be your answer here, with an Ethernet shield connected to an Arduino UNO. I have not got the equipment to test this. I have been speaking with @witnessmenow who said he may be able to test this, but that was in the early days of this library (even though it's a very new library!) and he's a busy chap!!

Another approach that may help is using an ESP32 - the big brother of the ESP8266. According to - https://github.com/JeroenBeemster/ESP32-WPA2-enterprise this works. There is also some promise in this example here - https://www.esp32.com/viewtopic.php?f=2&t=3108. My library "should" work with the ESP32 boards. Again i've not got an ESP32 yet so cannot confirm it works or not without issue. I think this may be the best solution if it works - you can get a dev board like http://s.click.aliexpress.com/e/fuz7m6U for about £6 (I use that seller a lot in the link, they are good!). Run the WPA2 examples to make sure it connects OK to your network, then merge into my HelloWorldSerial example... touch wood....  

Time to buy myself an ESP32 I think.

Steve

**Comment by mullinsen** [comment]
Thank you very much! 
ESP32 seems promising. We will also have a look into SPI or I2C, because as the RPi and Arduino will be located close to each other, it would be nice to avoid the risk of a dodgy WiFi in certain areas and locations. Ethernet is also preferable to avoid, as the RPi already will be connected with Ethernet. Two ethernet cables for one robot is rather excessive.... If we do not find any better solutions we will probably go for the ESP32 - this seems to be the most promising solution so far. 

Does the OctoPrintAPI library support sending commands to OctoPrint?

Really appreciate your help!

Michael

**Comment by chunkysteveo** [comment]
Hiya,

Physical cables are always preferred in industrial setups, so you can't go too wrong NOT choosing WiFi in critical applications!

The library does not support sending any commands at the moment, just "GET" endpoints of the API. I do plan to add this in - it's a very young library - POST requests to the OctoPrint server will be one of the things to complete further down the line, allowing you to start/stop/pause jobs etc with push buttons or any event. The API for OctoPrint is very comprehensive - you can even send GCode terminal commands to the printer too. Most actions done on the server with the Web GUI can be done via the API.... I just have to write it!

Best of luck with the thesis!

Steve

**Comment by chunkysteveo** [comment]
Ethernet "should" work now, it wouldn't have worked previously. But now it probably should may will work... if you are going down this path!

Steve

**Comment by mullinsen** [comment]
Thank you!
We have however decided to go a different path, using Firmata to communicate with Python, where we will use https://github.com/dragondgold/octo-control/blob/master/octo-control.py to communicate with OctoPrint API, as this can communicate both ways - using only physical cables.
Still, we thank you very much for your help!

Michael

**Comment by chunkysteveo** [comment]
Awesome, looks great! Best of luck with your thesis!

Steve
