### ISSUE TITLE
values not reset with printer not operational

### ISSUE THREAD

**Issue by fmatray** [chunkysteveo/OctoPrintAPI#22]
Hello,
When the printer is not operational, the function getPrinterStatistics() does not reset printerStats.printerStat* and printerStats.printer*Temp* values.
At least printerStats.printerStateoperational should be false;

``
      if(response == "Printer is not operational"){
        String printerState = response;
        printerStats.printerState = printerState;
        return true;
      }
``

**Comment by chunkysteveo** [comment]
Now in new PR merge.
