### ISSUE TITLE
Update OctoprintApi::getPrinterStatistics() to match Octoprint

### ISSUE THREAD

**Issue by fmatray** [chunkysteveo/OctoPrintAPI#24]
Hello,
Status pausing and cancelling are missing in Octoprint OctoprintApi::getPrinterStatistics().

I can add it this week, if you are ok.

**Comment by chunkysteveo** [comment]
Yeah, I saw those as new states when I was playing with my printer and Home Assistant... You can certainly add them in if you like, or no rush and I can add them if you like?

**Comment by fmatray** [comment]
I did it yesterday. I have a project to supervise the printer.
Two weeks ago we almost burn the printer (and the house) down.

**Comment by chunkysteveo** [comment]
You're a legend, you have more time than me to keep this up! I'll get a new version number up soon and dedicate it to your hard work!

I've had a few near misses... glad this is being put to good use and will keep you safe!

**Comment by fmatray** [comment]
I just have time those days as I don't work because of the lockdown.
