### ISSUE TITLE
OctoprintApi::getPrintJob() update to match the API

### ISSUE THREAD

**Issue by fmatray** [chunkysteveo/OctoPrintAPI#26]
Hello,
The api for job have an update with 'printTimeOrigin' :
https://docs.octoprint.org/en/master/api/datamodel.html#progress-information

This information give the calculation method for printTimeLeft.

I'm not sure this is very useful for this library.
What do you think ?

**Comment by chunkysteveo** [comment]
It could be useful if someone was to colour code the estimate similar to the Web GUI - red, amber, green etc?

**Comment by fmatray** [comment]
Done :-)
