### ISSUE TITLE
Library version issue

### ISSUE THREAD

**Issue by bobcroft** [chunkysteveo/OctoPrintAPI#32]
Hi, today I tried to compile the OctoPlugOut code, shared by Ruud Rademaker on the OctoPrint forum, using platformIO.  I had an issue with the  version of your library the platformIO downloaded 1.1.4 which appears to be the latest.  However, it would not compile complaining of missing 'api.octoPrintCoreShutdown'.  When I manually downloaded the library from Github as a zip file and then manually installed it in platformIO everything compiled correctly.  I note that the most recent changes to the library include the missing item so I wondered if there is a versioning issue between what platformIO picks up and what is downloaded manually.

**Comment by chunkysteveo** [comment]
hiya,

Yes - that may well be the case - i've not set the library to work well with Platform IO as i've built it separate from that (old school!).  This is probably the same issue as [this issue](https://github.com/chunkysteveo/OctoPrintAPI/issues/18) about adding a manifest? I've not looked into it yet due to being busy, but if you have an update to make it work within Platform IO - pull requests are always welcome!!!! 😄 

Steve

**Comment by chunkysteveo** [comment]
I've not updates the Arduino Library version for a while too.... I am the WORST programmer, haha!!!

**Comment by bobcroft** [comment]
Hi Stephen,

 

I think I might challenge you for the title of worst programmer.  I am only an amateur and still learning platformIO,(PIO) I do like PIO as it is streets ahead of the ArduinoIDE.

The basic problem is that PIO downloads your library 1.1.4 but the version it download does not include your latest changes made as a result of Ruud’s pull request, the last three api functions.  Thus when PIO tries to compile the code it cannot find those three api functions  and fails.

I don’t know but I wondered if you update the library to 1.1.5 it would make PIO pull the latest library with all the changes.

I think it would be really good if your library can be made to work with PIO as a standard install because I believe Ruud’s octoPrintOut is a good project, although personally I would build my own switch box.

If I knew how to make the changes to your library I would offer to assist but I don’t, sorry.

Can you let me know when you make a change and I’ll try it again in PIO.

 

Bob

**Comment by chunkysteveo** [comment]
Have bumped the release version up to 1.1.5 as a test. Let me know how that goes now?

Steve

**Comment by bobcroft** [comment]
Hi Stephen,

 

Very happy to report library now loads successfully in platformIO as 1.1.5. and compiles properly too.  Now to get OTA working correctly and checks Ruud’s project talks to the RPi.

I would like to congratulate you on a good application for the 3D printers. I’ll look at your other stuff too.

 

Bob

**Comment by chunkysteveo** [comment]
Thats awesome news Bob. Thanks for letting me know it worked. Best of luck with Ruud's project!
