### ISSUE TITLE
Pushing Temperature of enclosure to Octoprint

### ISSUE THREAD

**Issue by SaKiEQ** [chunkysteveo/OctoPrintAPI#34]
Would it be possible to make a small arduino temperature and humidity reader, that pushes the temp to of the enclosure to octoprint. It seems that the latency of some sensors can be a bit of an issue on Raspberry GPIO, this way a local Arduino with LCD display can do the reading and push temperatures on a regular interval to Octoprint/Pi.

**Comment by chunkysteveo** [comment]
The chamber commands on Octoprint read from the printer and pushes commands to the printer to increase or decrease (do not heat) the chamber. The sensor comes from the printer and commands are sent to the printer. I don't think the API would be interfacing with sensors onboard the GPIOs? Sounds like a great idea, but probably a little outside the scope of this library?

Steve

**Comment by SaKiEQ** [comment]
Octoprint can read a DH22 sensor on the GPIO pins, my idea was to read and
buffer the reading on a Arduino and sending
the information to Octoprint instead of bothering the PI with that task.
This would give me a option of attaching a simple I2C display
to the Arduino for direct display of the values, as the Octoprint would not
need the humidity but only the temp.

Heating of enclosure would be controlled by Octoprint/Printer.

**Comment by SaKiEQ** [comment]
for your reference, a Octoprint plugin that reads a directly connected to the rasPI and deals with the Octoprint plugin API. 

https://github.com/vitormhenrique/OctoPrint-Enclosure

In my case i would be interested to have a Arduino do the work to display values to a local LCD, maybe even do some environmental controls directly, while interfacing with Octopi to just push temp readings, circumventing the mentioned latency / priority issues of the sensor GPIO reads.

**Comment by chunkysteveo** [comment]
Will update the API if/when the API from Octoprint pushes the enclosure temps as a standard endpoint.
